#!/bin/bash

PUBLIC_IP=$1                  # Public IP is first parameter
PUBLIC_SUBNET=${PUBLIC_IP%.*} # Sunbnet is found by deleting the last IP digits
NETWORK_ADAPTER=$2            # Network adater is second parameter

echo "Forwarding all SSH access attempts to public IP $PUBLIC_IP"
echo "to local network adater $NETWORK_ADAPTER port 22..."
echo ""

echo "ip rule add from ${PUBLIC_IP} table 128"
ip rule add from ${PUBLIC_IP} table 128

echo "ip route add table 128 to ${PUBLIC_SUBNET}.128/25 dev ${NETWORK_ADAPTER}"
ip route add table 128 to ${PUBLIC_SUBNET}.128/25 dev ${NETWORK_ADAPTER}

echo "ip route add table 128 default via ${PUBLIC_SUBNET}.129"
ip route add table 128 default via ${PUBLIC_SUBNET}.129

echo "iptables -A INPUT -d ${PUBLIC_IP} -p tcp --dport 22 -j ACCEPT"
iptables -A INPUT -d ${PUBLIC_IP} -p tcp --dport 22 -j ACCEPT

echo "iptables -A INPUT -d ${PUBLIC_IP} -j DROP"
iptables -A INPUT -d ${PUBLIC_IP} -j DROP