#!/bin/bash -e

for i in {0..10}; do
  if [ "$(ifconfig -a | grep vboxnet${i})" != "" ]; then
    echo "ifconfig vboxnet${i} 192.168.$((${i}+1)).1 netmask 255.255.255.0 up"
    ifconfig vboxnet${i} 192.168.$((${i}+1)).1 netmask 255.255.255.0 up
  fi
done
