#!/bin/bash

for i in $(ls ~ | grep -E "macro[0-9]*"); do
   echo "mkdir -p ~/$i/woh/build"
   mkdir -p ~/$i/woh/build

   echo "sudo mount -t tmpfs -o size=80M tmpfs ~/$i/woh/build"
   sudo mount -t tmpfs -o size=80M tmpfs ~/$i/woh/build
done