#!/bin/bash

TESS_ROOT="/home/me/clash/amacro/tesseract/tesseract-ocr/build/bin"

cp ../../../coc_training_text.txt training_text.txt

"${TESS_ROOT}"/text2image --text=training_text.txt --outputbase=non.Supercell-Magic.exp0 --fonts_dir=/home/me/clash/amacro/tesseract/fonts --font='Supercell-Magic'

##
## MAKE CHANGES IF NEED BE
##

"${TESS_ROOT}"/tesseract non.Supercell-Magic.exp0.tif non.Supercell-Magic.exp0 nobatch box.train

#or
#tesseract non.wohnumbers.exp0.png non.wohnumbers.exp0 nobatch box.train.stderr


# Generate the known set of characters:
"${TESS_ROOT}"/unicharset_extractor non.Supercell-Magic.exp0.box

# Generate font info / clustering
# format: <fontname> <italic> <bold> <fixed> <serif> <fraktur>
echo -e "Supercell-Magic 0 1 1 0 0" > font_properties
"${TESS_ROOT}"/shapeclustering -F font_properties -U unicharset non.Supercell-Magic.exp0.tr

"${TESS_ROOT}"/mftraining -F font_properties -U unicharset -O non.unicharset non.Supercell-Magic.exp0.tr
rm unicharset

"${TESS_ROOT}"/cntraining non.Supercell-Magic.exp0.tr

# Combining everything:

mv inttemp non.inttemp
mv normproto non.normproto
mv pffmtable non.pffmtable
mv shapetable non.shapetable

"${TESS_ROOT}"/combine_tessdata non.

cp non.traineddata ../tesseract-ocr/build/share/tessdata/
